In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np


In [8]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)


1.16.4


In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))

In [5]:
#4. Print a.
print(a)

[[[0.69032154 0.48605073 0.64753892 0.88950054 0.70915224]
  [0.91226041 0.90813681 0.02660409 0.10195266 0.17503161]
  [0.22714011 0.02287659 0.63526054 0.85953202 0.57132175]]

 [[0.33513924 0.93956535 0.48913648 0.798078   0.49152393]
  [0.22592059 0.06561766 0.70718225 0.62622094 0.52182445]
  [0.27912138 0.09612072 0.26827116 0.33266781 0.09488129]]]


In [6]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))

In [7]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [8]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size ==b.size

True

In [9]:
#8. Are you able to add a and b? Why or why not?
np.add(a+b)
# not addible because different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [10]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
one_array=np.sum(b, axis=0)
x=np.ones((1,3))
y=np.ones((3,2))
full_rows= np.vstack([one_array,x])
full_shape=np.hstack([full_rows,y])
print(full_shape)
c=2* full_shape
print(c)

[[5. 5. 5. 1. 1.]
 [5. 5. 5. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[10. 10. 10.  2.  2.]
 [10. 10. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


In [11]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.add(a,c)
print(d)
# the shape is the right one now (2,3,5)

[[[10.69032154 10.48605073 10.64753892  2.88950054  2.70915224]
  [10.91226041 10.90813681 10.02660409  2.10195266  2.17503161]
  [ 2.22714011  2.02287659  2.63526054  2.85953202  2.57132175]]

 [[10.33513924 10.93956535 10.48913648  2.798078    2.49152393]
  [10.22592059 10.06561766 10.70718225  2.62622094  2.52182445]
  [ 2.27912138  2.09612072  2.26827116  2.33266781  2.09488129]]]


In [12]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
#each item of array a is added to each item of array in d

[[[0.69032154 0.48605073 0.64753892 0.88950054 0.70915224]
  [0.91226041 0.90813681 0.02660409 0.10195266 0.17503161]
  [0.22714011 0.02287659 0.63526054 0.85953202 0.57132175]]

 [[0.33513924 0.93956535 0.48913648 0.798078   0.49152393]
  [0.22592059 0.06561766 0.70718225 0.62622094 0.52182445]
  [0.27912138 0.09612072 0.26827116 0.33266781 0.09488129]]]
[[[10.69032154 10.48605073 10.64753892  2.88950054  2.70915224]
  [10.91226041 10.90813681 10.02660409  2.10195266  2.17503161]
  [ 2.22714011  2.02287659  2.63526054  2.85953202  2.57132175]]

 [[10.33513924 10.93956535 10.48913648  2.798078    2.49152393]
  [10.22592059 10.06561766 10.70718225  2.62622094  2.52182445]
  [ 2.27912138  2.09612072  2.26827116  2.33266781  2.09488129]]]


In [13]:
#12. Multiply a and c. Assign the result to e.
e= np.multiply(a,c)
print(e)

[[[6.90321545 4.86050727 6.47538924 1.77900108 1.41830448]
  [9.12260405 9.08136813 0.2660409  0.20390532 0.35006322]
  [0.45428022 0.04575319 1.27052108 1.71906404 1.14264349]]

 [[3.35139239 9.39565354 4.89136479 1.596156   0.98304786]
  [2.25920585 0.65617664 7.07182247 1.25244189 1.0436489 ]
  [0.55824275 0.19224144 0.53654232 0.66533562 0.18976258]]]


In [14]:
#13. Does e equal to a? Why or why not?
e==a
# because types are the same?

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

In [15]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("Max: ",d_max, "Min: ",d_min, "Mean:",d_mean)

Max:  10.93956535404966 Min:  2.0228765933427106 Mean: 5.671131727035749


In [16]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty([2,3,5], dtype= int)
print(f)

[[[         0 1076101120          0 1076101120          0]
  [1076101120          0 1073741824          0 1073741824]
  [         0 1076101120          0 1076101120          0]]

 [[1076101120          0 1073741824          0 1073741824]
  [         0 1073741824          0 1073741824          0]
  [1073741824          0 1073741824          0 1073741824]]]


"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [17]:

outlist= [i for i in d.tolist()]

list_in_list= [i for sublist in outlist for i in sublist]

final_list= [i for subsublist in list_in_list for i in subsublist]
list_change= [0 if i == d_min else 25 if i < d_mean else 50 if i == d_mean else 75 if i <d_max else 100 for i in final_list]
np.array(list_change)
f = np.array(list_change).reshape(2,3,5)
print(f)

[[[ 75  75  75  25  25]
  [ 75  75  75  25  25]
  [ 25   0  25  25  25]]

 [[ 75 100  75  25  25]
  [ 75  75  75  25  25]
  [ 25  25  25  25  25]]]


In [18]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print("Array d: ", d, "\n", "Array f:",f)

Array d:  [[[10.69032154 10.48605073 10.64753892  2.88950054  2.70915224]
  [10.91226041 10.90813681 10.02660409  2.10195266  2.17503161]
  [ 2.22714011  2.02287659  2.63526054  2.85953202  2.57132175]]

 [[10.33513924 10.93956535 10.48913648  2.798078    2.49152393]
  [10.22592059 10.06561766 10.70718225  2.62622094  2.52182445]
  [ 2.27912138  2.09612072  2.26827116  2.33266781  2.09488129]]] 
 Array f: [[[ 75  75  75  25  25]
  [ 75  75  75  25  25]
  [ 25   0  25  25  25]]

 [[ 75 100  75  25  25]
  [ 75  75  75  25  25]
  [ 25  25  25  25  25]]]


In [36]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'

In [19]:
list_change= ["A" if i == d_min else "B" if i < d_mean else "C" if i == d_mean else "D" if i <d_max else "E" for i in final_list]
np.array(list_change)
g = np.array(list_change).reshape(2,3,5)
print(g)

[[['D' 'D' 'D' 'B' 'B']
  ['D' 'D' 'D' 'B' 'B']
  ['B' 'A' 'B' 'B' 'B']]

 [['D' 'E' 'D' 'B' 'B']
  ['D' 'D' 'D' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']]]
