In [6]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [7]:
#2. Print the NUMPY version and the configuration.

print (np.version.version)
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

In [8]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))

In [9]:
#4. Print a.

print(a)

[[[0.87156993 0.54416174 0.02211388 0.73106509 0.49201036]
  [0.3943787  0.79403099 0.12081847 0.87338723 0.60764808]
  [0.44026617 0.84967396 0.16480663 0.30346534 0.9704769 ]]

 [[0.5027386  0.00594679 0.84102142 0.97863523 0.53916629]
  [0.3142868  0.66235914 0.39240787 0.8719673  0.77200129]
  [0.01261622 0.58710023 0.03955135 0.79285381 0.39019066]]]


In [10]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3), dtype = int)

In [11]:
#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [12]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size)

b.size


30


30

In [13]:
#8. Are you able to add a and b? Why or why not?

np.add(a,b)

#No due to the diferent formats (nr of lines and nr of columns)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [14]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b,(1,2,0))

In [15]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = np.add(a,c)
#it works due to similiar shapes of arrays

In [16]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print (a)
"\n"
print (d)

#all values in d are a values + 1 since a values are random values between 0-1

[[[0.87156993 0.54416174 0.02211388 0.73106509 0.49201036]
  [0.3943787  0.79403099 0.12081847 0.87338723 0.60764808]
  [0.44026617 0.84967396 0.16480663 0.30346534 0.9704769 ]]

 [[0.5027386  0.00594679 0.84102142 0.97863523 0.53916629]
  [0.3142868  0.66235914 0.39240787 0.8719673  0.77200129]
  [0.01261622 0.58710023 0.03955135 0.79285381 0.39019066]]]
[[[1.87156993 1.54416174 1.02211388 1.73106509 1.49201036]
  [1.3943787  1.79403099 1.12081847 1.87338723 1.60764808]
  [1.44026617 1.84967396 1.16480663 1.30346534 1.9704769 ]]

 [[1.5027386  1.00594679 1.84102142 1.97863523 1.53916629]
  [1.3142868  1.66235914 1.39240787 1.8719673  1.77200129]
  [1.01261622 1.58710023 1.03955135 1.79285381 1.39019066]]]


In [17]:
#12. Multiply a and c. Assign the result to e.

e = np.multiply (a,c)

In [18]:
#13. Does e equal to a? Why or why not?

e == a 
# due to multiplication between individual values and one of the arrays is fully composed of ones

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [19]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [20]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))


In [21]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question."
"""
print (d)
"""
f = np.where(d == d_max, 100, d)
f = np.where(f == d_min, 0, f)
f = np.where(f == d_mean, 50, f)
"""
def change_number (number):
    if (number>d_min and number<d_mean):
        return(25)
    elif (number>d_mean and number<d_max):
        return (75)
    elif (number==d_mean):
        return(50)
    elif (number==d_min):
        return (0)
    else:
        return (100)
    
f=[change_number(i) for sub_list in d for lst in sub_list for i in lst]

f=(np.array(f)).reshape(2,3,5)
#[i for [i, in d if d_max < i > d_mean = 75 elif i == d_mean =50 elif i == d_min =0 elif i == d_max =100 else i = 25]
print (f)


[[[1.87156993 1.54416174 1.02211388 1.73106509 1.49201036]
  [1.3943787  1.79403099 1.12081847 1.87338723 1.60764808]
  [1.44026617 1.84967396 1.16480663 1.30346534 1.9704769 ]]

 [[1.5027386  1.00594679 1.84102142 1.97863523 1.53916629]
  [1.3142868  1.66235914 1.39240787 1.8719673  1.77200129]
  [1.01261622 1.58710023 1.03955135 1.79285381 1.39019066]]]
[[[ 75  75  25  75  25]
  [ 25  75  25  75  75]
  [ 25  75  25  25  75]]

 [[ 25   0  75 100  75]
  [ 25  75  25  75  75]
  [ 25  75  25  75  25]]]


In [22]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

print (f)
print (d)

#f looks well defined looking at max_d and min_d

[[[ 75  75  25  75  25]
  [ 25  75  25  75  75]
  [ 25  75  25  25  75]]

 [[ 25   0  75 100  75]
  [ 25  75  25  75  75]
  [ 25  75  25  75  25]]]
[[[1.87156993 1.54416174 1.02211388 1.73106509 1.49201036]
  [1.3943787  1.79403099 1.12081847 1.87338723 1.60764808]
  [1.44026617 1.84967396 1.16480663 1.30346534 1.9704769 ]]

 [[1.5027386  1.00594679 1.84102142 1.97863523 1.53916629]
  [1.3142868  1.66235914 1.39240787 1.8719673  1.77200129]
  [1.01261622 1.58710023 1.03955135 1.79285381 1.39019066]]]


In [60]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'