In [2]:
#1. Import the NUMPY package under the name np.

import numpy as np


In [3]:
#2. Print the NUMPY version and the configuration.

np.version.version


'1.16.4'

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

a=np.random.random((2,3,5))

# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
#4. Print a.
a

array([[[0.24781208, 0.95361295, 0.6597609 , 0.82154109, 0.9600985 ],
        [0.15627624, 0.96528338, 0.16123838, 0.37821321, 0.05293369],
        [0.75628723, 0.0169338 , 0.02715257, 0.21955648, 0.9977765 ]],

       [[0.21587652, 0.90177404, 0.32491287, 0.60958456, 0.79374542],
        [0.36692654, 0.42090363, 0.29666983, 0.64249614, 0.42737415],
        [0.15958388, 0.2694397 , 0.44544074, 0.93508601, 0.45897371]]])

In [6]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b=np.ones((5,2,3))

In [7]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size==b.size

True

In [9]:
#8. Are you able to add a and b? Why or why not?

#no because the shapes do not match
print(a.shape)
print(b.shape)



(2, 3, 5)
(5, 2, 3)


In [10]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c=b.transpose((1,2,0))

#5, which occupied the position 0, goes to 3rd dimension, so "0" in the transposed, occupies the 3rd position.

In [11]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now
print("a shape is:", a.shape)
print("c shape is:", c.shape)

d=a+c

a shape is: (2, 3, 5)
c shape is: (2, 3, 5)


In [12]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print("a=", a)
print("d=", d)

#d is each value of "a" plus 1, which was what we had definied for array "b"

a= [[[0.24781208 0.95361295 0.6597609  0.82154109 0.9600985 ]
  [0.15627624 0.96528338 0.16123838 0.37821321 0.05293369]
  [0.75628723 0.0169338  0.02715257 0.21955648 0.9977765 ]]

 [[0.21587652 0.90177404 0.32491287 0.60958456 0.79374542]
  [0.36692654 0.42090363 0.29666983 0.64249614 0.42737415]
  [0.15958388 0.2694397  0.44544074 0.93508601 0.45897371]]]
d= [[[1.24781208 1.95361295 1.6597609  1.82154109 1.9600985 ]
  [1.15627624 1.96528338 1.16123838 1.37821321 1.05293369]
  [1.75628723 1.0169338  1.02715257 1.21955648 1.9977765 ]]

 [[1.21587652 1.90177404 1.32491287 1.60958456 1.79374542]
  [1.36692654 1.42090363 1.29666983 1.64249614 1.42737415]
  [1.15958388 1.2694397  1.44544074 1.93508601 1.45897371]]]


In [13]:
#12. Multiply a and c. Assign the result to e.
e=a*c
e

array([[[0.24781208, 0.95361295, 0.6597609 , 0.82154109, 0.9600985 ],
        [0.15627624, 0.96528338, 0.16123838, 0.37821321, 0.05293369],
        [0.75628723, 0.0169338 , 0.02715257, 0.21955648, 0.9977765 ]],

       [[0.21587652, 0.90177404, 0.32491287, 0.60958456, 0.79374542],
        [0.36692654, 0.42090363, 0.29666983, 0.64249614, 0.42737415],
        [0.15958388, 0.2694397 , 0.44544074, 0.93508601, 0.45897371]]])

In [14]:
#13. Does e equal to a? Why or why not?
e==a

#because we are multiplying each value of "a" by one, so it remais the same number

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [15]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9977764996505645
1.0169337969471526
1.4881088242809501


In [16]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty([2, 3, 5])
print(f)
type(f)

[[[0.24781208 0.95361295 0.6597609  0.82154109 0.9600985 ]
  [0.15627624 0.96528338 0.16123838 0.37821321 0.05293369]
  [0.75628723 0.0169338  0.02715257 0.21955648 0.9977765 ]]

 [[0.21587652 0.90177404 0.32491287 0.60958456 0.79374542]
  [0.36692654 0.42090363 0.29666983 0.64249614 0.42737415]
  [0.15958388 0.2694397  0.44544074 0.93508601 0.45897371]]]


numpy.ndarray

In [41]:
'''16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
'''

'''
25 if (number>d_min and number<d_mean)
75 if (number>d_mean and number<d_max)
50 if (number==d_mean)
0 if (number==d_min)
100 if (number==dmax)
'''



'''
def change_number (number):
    if (number>d_min and number<d_mean):
        return(25)
    elif (number>d_mean and number<d_max):
        return (75)
    elif (number==d_mean):
        return(50)
    elif (number==d_min):
        return (0)
    else:
        return (100)

f=[change_number(i) for sub_list in d for lst in sub_list for i in lst]
#f is a list, how can I do it whitout transforming into a list?
print(type(f))

print(f)

f=(np.array(f)).reshape(2,3,5)

print(f)
'''


'''
find the matrix with the maximum
matrix_max = d == d_max

#max has value 100
matrix_max = 100 * matrix_max
print(matrix_max)

matrix_mean = d == d_mean
matrix_mean = 50 * matrix_mean
print(matrix_mean)


matrix_min_mean = (d<d_mean) * (d>d_min)
matrix_min_mean = matrix_min_mean*25
print(matrix_min_mean)

matrix_max_mean=(d<d_max) * (d>d_mean)
matrix_max_mean=matrix_max_mean*75
print(matrix_max_mean)

final_matrix=matrix_max_mean+matrix_min_mean+matrix_mean+matrix_max
print(final_matrix)
'''

matrix_max = d == d_max
matrix_mean = d >= d_mean
matrix_more_min = d>d_min
matrix_more_mean = d>d_mean 

f_fin = 25 * matrix_more_min + 25 * matrix_mean + 25 * matrix_more_mean + 25 * matrix_max
print("\nOutput array: \n\n", f_fin)





Output array: 

 [[[ 25  75  75  75  75]
  [ 25  75  25  25  25]
  [ 75   0  25  25 100]]

 [[ 25  75  25  75  75]
  [ 25  25  25  75  25]
  [ 25  25  25  75  25]]]


In [93]:
'''#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
        '''

print(d)
print(f)

[[[1.06960829 1.93701286 1.44026263 1.36951956 1.60693662]
  [1.56097304 1.2361396  1.86086856 1.89858579 1.40592551]
  [1.23099357 1.15469339 1.82316834 1.15255183 1.84324367]]

 [[1.40215505 1.21679655 1.58745592 1.1264603  1.30737119]
  [1.7839973  1.85533137 1.36484617 1.62459929 1.17306184]
  [1.18073225 1.68638654 1.78602503 1.6961053  1.08339538]]]
[[[  0 100  25  25  75]
  [ 75  25  75  75  25]
  [ 25  25  75  25  75]]

 [[ 25  25  75  25  25]
  [ 75  75  25  75  25]
  [ 25  75  75  75  25]]]


In [94]:
'''
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
'''

def change_number_letter (number):
    if (number>d_min and number<d_mean):
        return("A")
    elif (number>d_mean and number<d_max):
        return ("B")
    elif (number==d_mean):
        return("C")
    elif (number==d_min):
        return ("D")
    else:
        return ("E")

g=[change_number_letter(i) for sub_list in d for lst in sub_list for i in lst]
#f is a list, how can I do it whitout transforming into a list?
print(type(f))

print(g)

g=(np.array(f)).reshape(2,3,5)

print(g)

<class 'numpy.ndarray'>
['D', 'E', 'A', 'A', 'B', 'B', 'A', 'B', 'B', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'B', 'A']
[[[  0 100  25  25  75]
  [ 75  25  75  75  25]
  [ 25  25  75  25  75]]

 [[ 25  25  75  25  25]
  [ 75  75  25  75  25]
  [ 25  75  75  75  25]]]
